---
image: qwe1/debdocker:24.0
#image: crazymax/docker:latest
services:
  - name: docker:24.0-dind
    command: ["--experimental"]
    # https://forum.gitlab.com/t/docker-dind-stops-working-after-12-1-0-update/28664/2
    # entrypoint: ["env", "-u", "DOCKER_HOST"]
    # command: ["dockerd-entrypoint.sh"]

variables:
  # for some reason docker on gitlab throws context errors with these enabled
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  #DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  #BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

stages:
  - build
  - push
  - test

build:
  stage: build
  script:
   - docker build -f f38 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:f38 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:fedora .
   - docker build -f al9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:al9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:el .
   - docker images
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:f38 cat /etc/os-release
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:f38 systemctl --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:al9 cat /etc/os-release
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:al9 systemctl --version   

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - docker build -f f38 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:f38 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:fedora .
   - docker build -f al9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:al9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:el .
   # summary
   - docker images
   #- docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:tag
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT --all-tags

test_docker_images:
 stage: test
 only:
   - master
 script:
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:f38 cat /etc/os-release
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:f38 systemctl --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:al9 cat /etc/os-release
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:al9 systemctl --version 
